export const EnvKeys = {
  PG_USERNAME: 'PG_USERNAME',
  PG_PASSWORD: 'PG_PASSWORD',
  PG_DATABASE: 'PG_DATABASE',
  PG_HOST: 'PG_HOST',
  PG_PORT: 'PG_PORT',
  MAILHOG_DB_TYPE: 'MAILHOG_DB_TYPE',
  MAILHOG_DB_PATH: 'MAILHOG_DB_PATH',
  MAIL_WEB_INTERFACE_PORT: 'MAIL_WEB_INTERFACE_PORT',
  MAIL_SMTP_PORT: 'MAIL_SMTP_PORT',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  MEILI_MASTER_KEY: 'MEILI_MASTER_KEY',
  MEILI_PORT: 'MEILI_PORT',
} as const;

export type EnvKeysType = keyof typeof EnvKeys;
