services:
  # DB
  database:
    image: postgres
    restart: on-failure
    container_name: CortexAccess
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    ports:
      - "${PG_PORT}:5432"


    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${PG_DATABASE} -U ${PG_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # MAILHOG
  # Ignore MailHog SQLite database /docker/mailHog_data/*
  mailHog:
    image: mailhog/mailhog
    container_name: 'mailhog'
    logging:
      driver: 'json-file'
    ports:
      - "${MAIL_WEB_INTERFACE_PORT}:8025" # Web interface
      - "${MAIL_SMTP_PORT}:1025" # SMTP server port
    environment:
      - MAILHOG_DB_TYPE=sqlite
      - MAILHOG_DB_PATH=/data/mailhog.db
    volumes:
      - ./mailHog_data:/data
    restart: unless-stopped

  # REDIS
  # Additionally : Install https://redis.io/insight/ in your computer
  redis:
    image: redis
    container_name: 'cache'
    ports:
      - "${REDIS_PORT}:6379"
    restart: always
    volumes:
      - ./redis_data:/data  # persist Redis data

  # MEILISEARCH
  # documentation https://www.meilisearch.com/docs/guides/misc/docker
  meilisearch:
    image: getmeili/meilisearch:v1.11
    container_name: meilisearch
    environment:
      MEILI_MASTER_KEY: '${MEILI_MASTER_KEY}'
    ports:
      - "${MEILI_PORT}:7700"
    volumes:
      - ./meilisearch_data:/meili_data  # persist Meilisearch data
